### ISSUE TITLE
Not working with 2023.3 core 

### ISSUE THREAD

**Issue by umtauscher** [hassio-addons/addon-uptime-kuma#51]
# Problem/Motivation

> The addon stopped working

## Expected behavior

> Addon continue to work after update

## Actual behavior

> HA Integration page show "(i) not loaded"

## Steps to reproduce

> update to core 2023.3

**Comment by frenck** [comment]
> HA Integration page show "(i) not loaded"

This is not an integration... you are mixing up things.

../Frenck

**Comment by umtauscher** [comment]
Sorry frenck,
but I find you reaction quite rude.
When I start search for integrations I get this dialog and installed it a while ago and it worked until yesterday..
![Bildschirmfoto 2023-03-03 um 17 58 59](https://user-images.githubusercontent.com/24495410/222781259-2bfbdc22-8c53-4546-8c11-537058e8ecb2.JPG)
If I put that issue to the wrong project, I apologize but I would find it very nice, if you would point me in the right direction.
Cheers

**Comment by ThrawnJL** [comment]
> Sorry frenck,
> but I find you reaction quite rude.
> When I start search for integrations I get this dialog and installed it a while ago and it worked until yesterday..
> ![Bildschirmfoto 2023-03-03 um 17 58 59](https://user-images.githubusercontent.com/24495410/222781259-2bfbdc22-8c53-4546-8c11-537058e8ecb2.JPG)
> If I put that issue to the wrong project, I apologize but I would find it very nice, if you would point me in the right direction.
> Cheers

I made the same mess up i think
This place is apparently for a full Kuma server running in hass where as our problem is with the hacs integration which just connects to a server 
https://github.com/meichthys/uptime_kuma

I think this is what we want :)

**Comment by frenck** [comment]
> but I find you reaction quite rude.

How?

You are reporting an issue with another project here, I'm just closing it because you are in the wrong place. And that is rude?

I'm not the one mixing up integrations vs add-ons.

This is an add-on, you are reporting an integration issue. Not related at all.

> If I put that issue to the wrong project, I apologize but I would find it very nice, if you would point me in the right direction.

Home Assistant doesn't have Uptime Kuma integration built-in, so it must be third-party. YOU downloaded and installed it, so YOU should be aware of where it came from, yet you have the balls to call me fucking rude? Please... go away, don't come back again.

../Frenck

**Comment by umtauscher** [comment]
@ThrawnJL 
Thanks!
